name: Feature Request
description: Suggest an idea for this project
title: "As a [type of user], I want [a goal] so that [benefit]"
labels: ["enhancement", "lifecycle/needs-triage"]
projects: ["mauroalderete/20"]
assignees:
  - mauroalderete
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: description
    attributes:
      label: Describe the feature
      description: What would you like to see added?
      placeholder: I would like to see...
    validations:
      required: true
  - type: input
    id: aditional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: I'm using...
    validations:
      required: false
