name: Labeling

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  pull-requests: write

jobs:
  call-labeling-workflow:
    uses: cedeirasf/CedMT-devops-workflows/.github/workflows/labeling.yml@v1
    secrets: inherit
